-- ============================================================================
-- SamSecure - BDD Commune - Migration 057
-- Fichier   : 057_commune_code_retour_libelles_accentues.sql
-- Objet     : realignement des libelles du catalogue code_retour (#171,
--             restes d'accents). Les douze migrations 025, 028, 029, 030,
--             034, 037, 041, 042, 043, 045, 048 et 050 ont seede leurs
--             libelles en ASCII, la ou 047 et 052 sont accentuees et ou la
--             consigne #116 impose le francais accentue pour tout texte
--             destine a l'ecran (l'enveloppe sert le libelle en `libelle`,
--             et en `error` quand la route n'emet pas de message propre).
--             Cette migration reecrit, en francais accentue, les 250
--             libelles concernes, alignes sur server/docs/codes_retour.md
--             (mis a jour dans le meme lot). Seuls les accents changent :
--             ni la formulation, ni le type, ni le code. Les valeurs
--             d'enumeration techniques citees dans un libelle (perpetuelle,
--             souscription, previsionnel, alloue, les noms de colonnes CSV
--             produit, reference, quantite, les parametres annee,
--             date_debut, date_fin) restent en ASCII : ce sont des codes,
--             pas des mots. Les libelles deja sans accent attendu
--             (par exemple "Contrat introuvable") ne sont pas reecrits.
--             Modele : migration 043 (INSERT ... ON CONFLICT (code) DO UPDATE
--             SET libelle). Le type est porte par l'INSERT pour un catalogue
--             incomplet, mais jamais reecrit sur un code existant.
-- Cible     : PostgreSQL 16 - base Commune, apres 052 (mot "commune" dans le
--             nom : migrate.js route sur commonPool). Numero 057 : 053 a 056
--             sont reserves aux chantiers paralleles (preuves, licences).
-- Exécution : npm run migrate:dev / migrate:staging, puis redemarrage de
--             l'API (catalogue charge au demarrage).
-- Rejouable : ON CONFLICT (code) DO UPDATE, un second passage reecrit a
--             l'identique. Aucun DDL, aucune suppression.
-- ============================================================================

BEGIN;

INSERT INTO code_retour (code, type, libelle) VALUES
  (2000, 'trace', 'Compte créé'),
  (2001, 'trace', 'Compte modifié'),
  (2002, 'trace', 'Compte activé'),
  (2003, 'trace', 'Compte désactivé'),
  (2004, 'trace', 'Désactivation planifiée'),
  (2005, 'trace', 'Planification levée'),
  (2006, 'trace', 'Mise en fonction planifiée'),
  (2007, 'erreur', 'Cet email est déjà utilisé'),
  (2010, 'trace', 'Mot de passe défini par un administrateur'),
  (2011, 'reserve', '[PREREQUIS] Mail de réinitialisation envoyé. Route inexistante'),
  (2012, 'reserve', '[PREREQUIS] Mot de passe réinitialisé par lien. Route inexistante'),
  (2013, 'succes', 'Mot de passe défini'),
  (2014, 'succes', 'Mot de passe généré'),
  (2017, 'erreur', 'Cette action doit être effectuée depuis l''interface'),
  (2018, 'trace', 'Mot de passe généré par un administrateur'),
  (2019, 'succes', 'Lien de réinitialisation généré'),
  (2020, 'trace', 'Groupe attribué'),
  (2021, 'trace', 'Groupe retiré'),
  (2022, 'trace', 'Exception de droit ajoutée'),
  (2023, 'trace', 'Exception de droit modifiée'),
  (2024, 'trace', 'Exception de droit supprimée'),
  (2025, 'succes', 'Lien de réinitialisation valide'),
  (2026, 'succes', 'Mot de passe réinitialisé'),
  (2028, 'trace', 'Lien de réinitialisation émis par un administrateur'),
  (2029, 'erreur', 'Compte désactivé, réactivation requise'),
  (2030, 'trace', 'Connexion réussie'),
  (2040, 'reserve', '[PREREQUIS] Exécution d''une planification à l''échéance. Aucun ordonnanceur n''existe'),
  (2051, 'erreur', 'Cet utilisateur n''est pas dans votre périmètre'),
  (3001, 'succes', 'Détail du contrat'),
  (3002, 'succes', 'Contrat créé'),
  (3003, 'succes', 'Contrat modifié'),
  (3004, 'succes', 'Contrat supprimé'),
  (3005, 'succes', 'Contrat archivé'),
  (3006, 'succes', 'Contrat restauré'),
  (3007, 'succes', 'Liste des contrats, archivés inclus'),
  (3011, 'erreur', 'Le libellé est obligatoire'),
  (3013, 'erreur', 'La date de début doit précéder la date de fin'),
  (3015, 'erreur', 'Éditeur introuvable'),
  (3016, 'erreur', 'Société signataire introuvable'),
  (3019, 'erreur', 'Ce rattachement créerait un cycle'),
  (3020, 'erreur', 'Suppression impossible : éléments liés'),
  (3021, 'avertissement', 'Parent non cadré, anomalie qualité enregistrée'),
  (3022, 'erreur', 'L''éditeur est obligatoire'),
  (3023, 'erreur', 'La société signataire est obligatoire'),
  (3025, 'erreur', 'La date de début est obligatoire'),
  (3026, 'erreur', 'Contrat archivé : modification impossible, restaurez-le d''abord'),
  (3027, 'erreur', 'Suppression impossible : contrat déjà validé, archivez-le'),
  (3028, 'erreur', 'Contrat déjà archivé'),
  (3029, 'erreur', 'Contrat non archivé'),
  (3101, 'succes', 'Détail de la commande'),
  (3102, 'succes', 'Commande créée'),
  (3103, 'succes', 'Commande modifiée'),
  (3104, 'succes', 'Commande supprimée'),
  (3111, 'erreur', 'Le libellé est obligatoire'),
  (3114, 'erreur', 'La société acheteuse est obligatoire'),
  (3115, 'erreur', 'Société acheteuse introuvable'),
  (3119, 'erreur', 'Le montant doit être strictement positif'),
  (3121, 'erreur', 'La date de fin doit être postérieure à la date de commande'),
  (3130, 'erreur', 'Suppression impossible : éléments liés'),
  (3140, 'succes', 'Agrégats financiers'),
  (3141, 'erreur', 'L''endpoint accepte soit annee, soit le couple date_debut / date_fin. Le précalcul étant mensuel, une plage au jour près est servie au mois près et les bornes appliquées sont renvoyées dans periode_debut et periode_fin.'),
  (3142, 'erreur', 'Identifiant de société invalide'),
  (3143, 'erreur', 'Identifiant d''éditeur invalide'),
  (3144, 'erreur', 'La période demandée est invalide'),
  (3201, 'succes', 'Détail de la preuve'),
  (3202, 'succes', 'Preuve créée'),
  (3203, 'succes', 'Preuve modifiée'),
  (3204, 'succes', 'Preuve supprimée'),
  (3205, 'succes', 'Fichier déposé'),
  (3211, 'erreur', 'Le libellé est obligatoire'),
  (3214, 'erreur', 'Une preuve doit être rattachée à un contrat, à une commande, ou aux deux'),
  (3218, 'erreur', 'L''empreinte SHA-256 doit comporter 64 caractères hexadécimaux'),
  (3220, 'erreur', 'Aucun fichier n''a été transmis'),
  (3221, 'erreur', 'Extension non admise, formats acceptés pdf png jpg jpeg'),
  (3222, 'erreur', 'Le fichier dépasse la taille maximale de 20 Mo (413)'),
  (3223, 'erreur', 'Le contenu du fichier ne correspond pas à son extension'),
  (3224, 'erreur', 'Aucun fichier n''a été déposé pour cette preuve'),
  (3226, 'erreur', 'Chemin de stockage invalide, traversée refusée'),
  (3227, 'erreur', 'Un seul fichier peut être déposé, dans le champ fichier'),
  (3230, 'erreur', 'Suppression impossible : preuve rattachée à une facture'),
  (3231, 'reserve', '[ARBITRAGE D27] lien externe GED refusé. Non émis à ce jour'),
  (3232, 'reserve', '[ARBITRAGE D27] redirection vers un lien GED externe. Non émis à ce jour'),
  (3241, 'succes', 'Détail de la facture'),
  (3242, 'succes', 'Facture créée'),
  (3243, 'succes', 'Facture modifiée'),
  (3244, 'succes', 'Facture supprimée'),
  (3245, 'succes', 'Facture et preuve créées en une transaction'),
  (3251, 'erreur', 'Le libellé est obligatoire'),
  (3255, 'reserve', '[ARBITRAGE flux] la preuve est obligatoire dès la création. Non émis à ce jour'),
  (3256, 'erreur', 'Le fichier justificatif est obligatoire, dépôt combiné'),
  (3281, 'erreur', 'Identifiant de société invalide'),
  (3283, 'erreur', 'L''année demandée est invalide'),
  (3300, 'succes', 'Saisie validée'),
  (3301, 'succes', 'Saisie refusée'),
  (3310, 'erreur', 'Type d''entité inconnu du workflow de validation'),
  (3311, 'erreur', 'Entité introuvable'),
  (3313, 'erreur', 'Seule une saisie en attente peut être traitée'),
  (4001, 'succes', 'Détail de la licence'),
  (4002, 'succes', 'Licence créée'),
  (4003, 'succes', 'Licence modifiée'),
  (4004, 'succes', 'Licence supprimée'),
  (4006, 'succes', 'Période de maintenance ajoutée'),
  (4007, 'succes', 'Période de maintenance modifiée'),
  (4008, 'succes', 'Période de maintenance supprimée'),
  (4009, 'succes', 'Maintenance arrêtée, version figée'),
  (4013, 'erreur', 'Édition introuvable ou étrangère au produit'),
  (4014, 'erreur', 'Version introuvable ou étrangère au produit'),
  (4017, 'erreur', 'Unité de mesure introuvable'),
  (4019, 'erreur', 'La quantité doit être un entier positif ou nul'),
  (4020, 'erreur', 'Le coût doit être un montant positif ou nul'),
  (4023, 'erreur', 'Suppression impossible : éléments liés'),
  (4030, 'erreur', 'Période de maintenance introuvable'),
  (4031, 'erreur', 'La date de début est obligatoire'),
  (4032, 'erreur', 'La date de fin doit être postérieure à la date de début'),
  (4033, 'erreur', 'Le coût de maintenance doit être un montant positif ou nul'),
  (4040, 'erreur', 'La maintenance de cette licence est déjà arrêtée'),
  (4041, 'erreur', 'La date d''arrêt est invalide'),
  (4042, 'erreur', 'Version à figer introuvable ou étrangère au produit'),
  (4043, 'erreur', 'Cette licence ne porte aucune maintenance à arrêter'),
  (4044, 'succes', 'Maintenance reprise, version libérée'),
  (4045, 'erreur', 'La maintenance de cette licence n''est pas arrêtée'),
  (4050, 'succes', 'Catalogue des produits (versions et éditions incluses)'),
  (4051, 'succes', 'Liste des unités de mesure'),
  (4059, 'erreur', 'Erreur serveur inattendue (référentiels du module licences)'),
  (4101, 'succes', 'Détail de l''affectation'),
  (4102, 'succes', 'Affectation déclarée et soumise à validation'),
  (4103, 'succes', 'Affectation modifiée et resoumise à validation'),
  (4104, 'succes', 'Affectation supprimée'),
  (4105, 'succes', 'Affectation revalidée, nouveau cycle ouvert'),
  (4106, 'succes', 'Décompte des usages déclarés pour la conformité'),
  (4107, 'succes', 'Historique des déclarations'),
  (4113, 'erreur', 'La société est obligatoire'),
  (4114, 'erreur', 'Société introuvable'),
  (4115, 'erreur', 'La quantité doit être un entier strictement positif'),
  (4116, 'erreur', 'La référence client est obligatoire'),
  (4117, 'erreur', 'Identifiant de société invalide'),
  (4130, 'erreur', 'Seule une affectation validée peut être revalidée'),
  (4132, 'erreur', 'Suppression impossible : affectation rapprochée d''un inventaire'),
  (4201, 'succes', 'Détail de l''import'),
  (4202, 'succes', 'Import d''inventaire effectué'),
  (4203, 'succes', 'Liste des relevés d''inventaire'),
  (4204, 'succes', 'Détail du relevé'),
  (4205, 'succes', 'Écarts d''inventaire'),
  (4206, 'succes', 'Relevé rapproché de l''affectation'),
  (4207, 'succes', 'Relevé marqué en écart assumé'),
  (4208, 'succes', 'Relevé rejeté'),
  (4209, 'succes', 'Relevé remis en attente'),
  (4211, 'avertissement', 'Import effectué avec des lignes en erreur'),
  (4221, 'erreur', 'Relevé introuvable'),
  (4222, 'erreur', 'Aucun fichier n''a été transmis'),
  (4223, 'erreur', 'Extension non admise, format accepté csv'),
  (4224, 'erreur', 'Le fichier dépasse la taille maximale de 20 Mo'),
  (4225, 'erreur', 'Un seul fichier peut être déposé'),
  (4228, 'erreur', 'Aucune ligne exploitable, import en échec'),
  (4229, 'erreur', 'Société introuvable'),
  (4233, 'erreur', 'Transition de statut non permise pour ce relevé'),
  (4235, 'reserve', 'Fichier archivé introuvable, contenu du relevé indisponible'),
  (4236, 'erreur', 'Le fichier dépasse le nombre maximal de lignes'),
  (4250, 'trace', 'Inventaire importé'),
  (4251, 'trace', 'Relevé rapproché'),
  (4252, 'trace', 'Relevé marqué en écart assumé'),
  (4253, 'trace', 'Relevé rejeté'),
  (4254, 'trace', 'Relevé remis en attente'),
  (5100, 'succes', 'Liste des lignes budgétaires'),
  (5101, 'succes', 'Détail de la ligne budgétaire'),
  (5102, 'succes', 'Ligne budgétaire créée'),
  (5103, 'succes', 'Ligne budgétaire modifiée'),
  (5104, 'succes', 'Ligne budgétaire supprimée'),
  (5105, 'succes', 'Projection prévisionnelle préremplie depuis la maintenance en cours'),
  (5106, 'succes', 'Engagé calculé depuis les commandes'),
  (5107, 'succes', 'Synthèse budgétaire : prévisionnel, alloué, engagé'),
  (5110, 'erreur', 'Ligne budgétaire introuvable'),
  (5113, 'erreur', 'Le type doit être previsionnel ou alloue'),
  (5114, 'erreur', 'La date de début est obligatoire'),
  (5116, 'erreur', 'La date de fin doit être postérieure ou égale à la date de début'),
  (5118, 'erreur', 'Le montant CAPEX doit être un montant positif ou nul'),
  (5119, 'erreur', 'La quantité CAPEX doit être un nombre positif ou nul'),
  (5120, 'erreur', 'Le montant OPEX doit être un montant positif ou nul'),
  (5121, 'erreur', 'La quantité OPEX doit être un nombre positif ou nul'),
  (5122, 'erreur', 'Une ligne budgétaire porte au moins un montant, CAPEX ou OPEX'),
  (5124, 'erreur', 'L''exercice demandé est invalide'),
  (5125, 'erreur', 'La période demandée est invalide'),
  (5126, 'erreur', 'Société introuvable'),
  (5131, 'avertissement', 'Licence sans commande, organisation payeuse indéterminée, exercice du tenant appliqué'),
  (5150, 'trace', 'Ligne budgétaire créée (audit_log BUDGET_CREE)'),
  (5151, 'trace', 'Ligne budgétaire modifiée (audit_log BUDGET_MODIFIE)'),
  (5152, 'trace', 'Ligne budgétaire supprimée (audit_log BUDGET_SUPPRIME)'),
  (5200, 'succes', 'Liste des éditeurs'),
  (5201, 'succes', 'Détail de l''éditeur'),
  (5202, 'succes', 'Éditeur créé'),
  (5203, 'succes', 'Éditeur modifié'),
  (5204, 'succes', 'Éditeur supprimé'),
  (5205, 'succes', 'Suggestions d''éditeurs'),
  (5210, 'erreur', 'Éditeur introuvable'),
  (5212, 'erreur', 'Un éditeur porte déjà cette raison sociale'),
  (5213, 'erreur', 'Suppression impossible : cet éditeur porte des rattachements'),
  (5221, 'succes', 'Détail du revendeur'),
  (5222, 'succes', 'Revendeur créé'),
  (5223, 'succes', 'Revendeur modifié'),
  (5224, 'succes', 'Revendeur désactivé'),
  (5225, 'succes', 'Revendeur réactivé'),
  (5230, 'erreur', 'Un revendeur porte déjà ce SIRET'),
  (5231, 'erreur', 'Un revendeur au nom très proche existe déjà'),
  (5234, 'erreur', 'Ce revendeur est déjà désactivé'),
  (5235, 'erreur', 'Ce revendeur est déjà actif'),
  (5236, 'erreur', 'Erreur serveur inattendue (référentiel revendeurs)'),
  (5237, 'trace', 'Revendeur créé'),
  (5238, 'trace', 'Revendeur modifié'),
  (5239, 'trace', 'Statut du revendeur modifié'),
  (5241, 'succes', 'Détail du contact'),
  (5242, 'succes', 'Contact créé'),
  (5243, 'succes', 'Contact modifié'),
  (5244, 'succes', 'Contact supprimé'),
  (5254, 'erreur', 'Un contact porte déjà cette adresse email'),
  (5255, 'erreur', 'Un contact au nom très proche existe déjà'),
  (5256, 'erreur', 'Erreur serveur inattendue (référentiel contacts)'),
  (5257, 'trace', 'Contact créé'),
  (5258, 'trace', 'Contact modifié'),
  (5259, 'trace', 'Contact supprimé'),
  (5290, 'trace', 'Éditeur créé'),
  (5291, 'trace', 'Éditeur modifié'),
  (5292, 'trace', 'Éditeur supprimé'),
  (5299, 'erreur', 'Erreur serveur inattendue (référentiel éditeurs)'),
  (5301, 'succes', 'Détail du logiciel'),
  (5302, 'succes', 'Logiciel créé'),
  (5303, 'succes', 'Logiciel modifié'),
  (5304, 'succes', 'Logiciel supprimé'),
  (5305, 'succes', 'Version ajoutée'),
  (5306, 'succes', 'Version supprimée'),
  (5307, 'succes', 'Édition ajoutée'),
  (5308, 'succes', 'Édition supprimée'),
  (5311, 'erreur', 'Le libellé est obligatoire'),
  (5312, 'erreur', 'Éditeur introuvable'),
  (5314, 'erreur', 'Un produit ne peut pas être son propre parent'),
  (5315, 'erreur', 'Ce rattachement fermerait une boucle dans la hiérarchie'),
  (5318, 'erreur', 'Le libellé de la version est obligatoire'),
  (5319, 'erreur', 'Cette version existe déjà pour ce logiciel'),
  (5320, 'erreur', 'Le libellé de l''édition est obligatoire'),
  (5321, 'erreur', 'Cette édition existe déjà pour ce logiciel'),
  (5323, 'erreur', 'Édition introuvable'),
  (5330, 'trace', 'Logiciel créé'),
  (5331, 'trace', 'Logiciel modifié'),
  (5332, 'trace', 'Logiciel supprimé'),
  (5399, 'erreur', 'Erreur serveur inattendue (référentiel logiciels)'),
  (5451, 'succes', 'Préférences de dashboard enregistrées'),
  (5452, 'succes', 'Synthèse des saisies et revalidations'),
  (5454, 'succes', 'Montants engagés et payés par éditeur'),
  (5460, 'erreur', 'L''axe demandé est invalide'),
  (5461, 'erreur', 'La période demandée est invalide'),
  (5462, 'erreur', 'Les préférences transmises sont invalides')
ON CONFLICT (code) DO UPDATE SET
  libelle = EXCLUDED.libelle;

COMMIT;
